### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/song_maker_gallery#52]
# Goals for Version 3 Release

## Frontend

- [ ] Student link submission (#10)
- [x] Gallery form (done) / demo gallery (#51)
- [x] Optimize, mainly though code splitting (#14)

## Backend

> TL;DR: the things needed to support those two things above.

I have not started to open issues for these, but feel free to open and ask about an issue if anyone reads this who is interested.

- [x] Rewrite `GallerySerializer` and remove gross data structure where the group name is the last array element
  - Instead, create a `GroupSerializer` that just serializes the id and name into a REST entity (#55)
  - Include that in the rendered gallery instead of the current `songData` mish-mosh.
- [x] Expose endpoints for RESTfully interacting with `Gallery`, `Group`, and `Song` entities individually (#59)
- [x] Create passthrough endpoint for on-demand service of MIDI / JSON data for a song to allow for instant previews on the frontend as described in #57.

**Comment by jdevries3133** [comment]
Released!!
